
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pqdata:/var/lib/postgresql/data
      - ./init/sql/init.sql:/init.sql
    ports:
      - "5430:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   
      - "9001:9001"   
    environment:
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_NOTIFY_KAFKA_ENABLE_avatar-events: "on"
      MINIO_NOTIFY_KAFKA_BROKERS_avatar-events: "kafka:29092"
      MINIO_NOTIFY_KAFKA_TOPIC_avatar-events: "avatar-events"
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"   
      - "9092:9092"     
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    healthcheck:
      test: kafka-topics --bootstrap-server kafka:29092 --list
      interval: 30s
      timeout: 10s
      retries: 3
    
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KAFKA_TOPIC: keycloak-events
      KAFKA_ADMIN_TOPIC: keycloak-admin-events
      KAFKA_CLIENT_ID: keycloak
      KAFKA_EVENTS: DELETE_ACCOUNT
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    command: start-dev
    depends_on:
      - postgres
      - kafka
    ports:
      - "7070:8080"
    restart: unless-stopped
    volumes:
    - ./init/keycloak-kafka/target/keycloak-kafka-1.4.0-jar-with-dependencies.jar:/opt/keycloak/providers/kafka.jar
  
  profile:
    build:
      context: ../profile/
      dockerfile: dockerfile
    container_name: profile
    environment:
      CONFIG: /root/profile.yaml
    volumes:
      - ./configs/profile.yaml:/root/profile.yaml
    depends_on:
      - keycloak
      - postgres 
      - minio 
      - kafka
    ports:
      - 8080:8080
    restart: unless-stopped
  
  chat:
    build:
      context: ../chat/
      dockerfile: dockerfile
    container_name: chat
    environment:
      CONFIG: /root/chat.yaml
    volumes:
      - ./configs/chat.yaml:/root/chat.yaml
    depends_on:
      - keycloak
      - postgres 
      - kafka
    ports:
      - 8081:8080
    restart: unless-stopped
  
  ws:
    build:
      context: ../websocket/
      dockerfile: dockerfile
    container_name: ws
    environment:
      CONFIG: /root/ws.yaml
    volumes:
      - ./configs/ws.yaml:/root/ws.yaml
    depends_on:
      - keycloak
      - kafka
    ports:
      - 8082:8080
    restart: unless-stopped

  # e2e:
  #   build:
  #     context: ../e2e/
  #     dockerfile: Dockerfile
  #   container_name: e2e
  #   environment:
  #     CONFIG: /root/e2e.yaml
  #   volumes:
  #     - ./configs/e2e.yaml:/root/e2e.yaml
  #   depends_on:
  #     - profile
    

volumes:
  miniodata:  
  pqdata:
  localstack-data: