
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - ./pq/data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   
      - "9001:9001"   
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    command: start-dev
    depends_on:
      - postgres
    ports:
      - "7070:8080"
    restart: unless-stopped

  tokenissuer-e2e:
    build:
      context: ../tokenissuer/
      dockerfile: dockerfile
    container_name: tokenissuer-e2e
    environment:
      CONFIG_PATH: /root/tokenissuer.yaml
    volumes:
      - ./configs/tokenissuer-e2e.yaml:/root/tokenissuer.yaml
    depends_on:
      - keycloak
    ports:
      - "50052:50052"

  tokenissuer-local:
    build:
      context: ../tokenissuer/
      dockerfile: dockerfile
    container_name: tokenissuer-local
    environment:
      CONFIG_PATH: /root/tokenissuer.yaml
    volumes:
      - ./configs/tokenissuer-local.yaml:/root/tokenissuer.yaml
    depends_on:
      - keycloak
    ports:
      - "50051:50051"
