
services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
    command: start-dev
    depends_on:
      - keycloak-db
    ports:
      - "7070:8080"
    restart: unless-stopped

  tokenissuer-e2e:
    build:
      context: ../tokenissuer/
      dockerfile: dockerfile
    container_name: tokenissuer-e2e
    environment:
      CONFIG_PATH: /root/tokenissuer.yaml
    volumes:
      - ./configs/tokenissuer-e2e.yaml:/root/tokenissuer.yaml
    depends_on:
      - keycloak
    ports:
      - "8083:8083"
      - "50052:50053"

  tokenissuer-local:
    build:
      context: ../tokenissuer/
      dockerfile: dockerfile
    container_name: tokenissuer-local
    environment:
      CONFIG_PATH: /root/tokenissuer.yaml
    volumes:
      - ./configs/tokenissuer-local.yaml:/root/tokenissuer.yaml
    depends_on:
      - keycloak
    ports:
      - "8081:8081"
      - "50051:50051"

volumes:
  keycloak-data:
