keycloak:
  refresh_endpoint: http://localhost:7070/realms/testrealm/protocol/openid-connect/token
  exchange_code_endpoint: http://localhost:7070/realms/testrealm/protocol/openid-connect/token
  jwks_endpoint: http://localhost:7070/realms/testrealm/protocol/openid-connect/certs
  client_id: tokenissuer
  client_secret: vlPJjw26XFRY1yYNOinKPTjzqb8vFmzX
  timeout: 30s

rest:
  host: 0.0.0.0
  port: 8081

grpc:
  host: 0.0.0.0
  port: 50051

verify_config:
  jwks_rate_limit: 5m