postgres:
  host: postgres
  port: 5432
  user: chat
  password: chat
  db_name: chat
  ssl_mode: disable

keycloak:
  jwks_endpoint: http://keycloak:8080/realms/main/protocol/openid-connect/certs

http: 
  host: 0.0.0.0 
  port: 8080
  debug_mode: true

migrations_path: file://migrations