postgres:
  host: postgres
  port: 5432
  user: chat
  password: chat
  db_name: chat
  ssl_mode: disable

keycloak:
  jwks_endpoint: http://keycloak:8080/realms/main/protocol/openid-connect/certs

http: 
  host: 0.0.0.0 
  port: 8080
  debug_mode: true

migrations_path: file://migrations

message_worker:
  kafka_producer: 
    brokers: 
    - kafka:29092 
    topic: message-event 
    retry: 1
    timeout: 5s
  delay: 10s
  messages_limit: 100
  users_limit: 10
