profile:
  auth: 
    url: http://keycloak:8080/realms/main/protocol/openid-connect/token
    client_id: main
    client_secret: main
    login: main
    password: main
    subject_id: 571e37b5-fdee-4aca-b941-5a26b5b0fb7e
  worker_delay: 30s
  delete_profile_url: "http://profile:8080/profile"
  add_profile_url: "http://profile:8080/profile"
  get_profile_url: "http://profile:8080/profile"
  upload_avatar_url: "http://profile:8080/avatar"