keycloak:
  refresh_endpoint: http://keycloak:8080/realms/main/protocol/openid-connect/token
  exchange_code_endpoint: http://keycloak:8080/realms/main/protocol/openid-connect/token
  jwks_endpoint: http://keycloak:8080/realms/main/protocol/openid-connect/certs
  client_id: tokenissuer
  client_secret: nWSMWegiBGWGJgA98bxdhy1eSB6KXcy8
  timeout: 30s

rest:
  host: 0.0.0.0
  port: 8081

grpc:
  host: 0.0.0.0
  port: 50051

verify_config:
  jwks_rate_limit: 5m